spring:
  jpa:
    generate-ddl: false
    hibernate:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type: trace
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


logging:
  level:
    ROOT: INFO
    org:
      hibernate:
        type:
          descriptor: trace
        SQL: debug